"""Compand gateway domain primitives."""

from .gateway import (
    ClientCredentialRegistry,
    CredentialAuthentication,
    GatewayMode,
    GatewaySecurityError,
    validate_upstream_origin,
)
from .scan import (
    LineRleCandidate,
    ScanEligibilityError,
    build_line_rle_candidate,
    decode_line_rle,
    encode_line_rle,
)
from .lab import (
    AppliedTransform,
    DetectionContext,
    EconomicsEstimate,
    LabArm,
    LabStage,
    LineRleTechnique,
    ReasonCode,
    StageStatus,
    Technique,
    TechniqueCandidate,
    VerificationProof,
    candidate_id_for,
    sha256_evidence,
)
from .techniques import (
    ALL_TECHNIQUE_IDS,
    SUPPORTED_TECHNIQUE_IDS,
    TECHNIQUE_REGISTRY,
    UNSUPPORTED_TECHNIQUE_IDS,
    get_registration,
    resolve_technique,
)
from .grading import (
    AblationArm,
    GRADE_WEIGHTS,
    HARD_GATE_IDS,
    KPI_IDS,
    interval_95,
    jcs_canonical_json_bytes,
    percentile,
    scorecard_sha256,
    weighted_grade,
)

__all__ = [
    "ClientCredentialRegistry",
    "CredentialAuthentication",
    "GatewayMode",
    "GatewaySecurityError",
    "validate_upstream_origin",
    "LineRleCandidate",
    "ScanEligibilityError",
    "build_line_rle_candidate",
    "decode_line_rle",
    "encode_line_rle",
    "AppliedTransform",
    "DetectionContext",
    "EconomicsEstimate",
    "LabArm",
    "LabStage",
    "LineRleTechnique",
    "ReasonCode",
    "StageStatus",
    "Technique",
    "TechniqueCandidate",
    "VerificationProof",
    "candidate_id_for",
    "sha256_evidence",
    "ALL_TECHNIQUE_IDS",
    "SUPPORTED_TECHNIQUE_IDS",
    "TECHNIQUE_REGISTRY",
    "UNSUPPORTED_TECHNIQUE_IDS",
    "get_registration",
    "resolve_technique",
    "AblationArm",
    "GRADE_WEIGHTS",
    "HARD_GATE_IDS",
    "KPI_IDS",
    "interval_95",
    "jcs_canonical_json_bytes",
    "percentile",
    "scorecard_sha256",
    "weighted_grade",
]
