"""Backward-compatible shim — prefer ``switchboard.storage.repositories.access``."""
import scripts.switchboard_path  # noqa: F401 — make src/switchboard importable

from switchboard.storage.repositories.access import (  # noqa: E402
    IDENTITY_RISK_WINDOW_S,
    _identity_risk_window_s,
    _identity_takeover_risk_in,
    _principal_from_row,
    _task_identity_state_in,
    create_auth_session,
    create_password_principal,
    create_principal,
    get_password_login,
    get_principal_by_id,
    get_principal_by_session,
    get_principal_by_session_any_project,
    get_principal_by_token,
    get_principal_by_token_any_project,
    list_principals,
    password_login_count,
    public_principal_record,
    resolve_write_actor,
    revoke_auth_session,
    revoke_principal,
    revoke_principal_sessions,
    revoke_principal_token,
    set_principal_password,
)

__all__ = [
    "IDENTITY_RISK_WINDOW_S",
    "create_principal",
    "public_principal_record",
    "list_principals",
    "get_principal_by_id",
    "get_principal_by_token",
    "get_principal_by_token_any_project",
    "password_login_count",
    "set_principal_password",
    "get_password_login",
    "create_password_principal",
    "create_auth_session",
    "get_principal_by_session",
    "get_principal_by_session_any_project",
    "revoke_auth_session",
    "revoke_principal_sessions",
    "revoke_principal",
    "revoke_principal_token",
    "resolve_write_actor",
    "_principal_from_row",
    "_identity_risk_window_s",
    "_task_identity_state_in",
    "_identity_takeover_risk_in",
]
