#!/usr/bin/env python3
"""ARCH-MS-6: pyproject.toml package scaffold (lockfile is ARCH-MS-13).

HARDEN-54 / PR #303 landed the scaffold; this test locks the Phase 0 contract:
abstract deps in pyproject.toml, Python 3.12 floor, non-package uv app layout,
and generated requirements exports. uv.lock reproducibility is ARCH-MS-13 scope.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

CORE_DEPS = (
    "fastapi>=",
    "uvicorn[standard]>=",
    "httpx>=",
    "mcp>=",
    "openpyxl>=",
)


def ok(condition, message):
    if not condition:
        raise AssertionError(message)


pyproject = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
python_version = (ROOT / ".python-version").read_text(encoding="utf-8").strip()
requirements = (ROOT / "requirements.txt").read_text(encoding="utf-8")
gateway_requirements = (ROOT / "deploy/gateway/requirements.txt").read_text(encoding="utf-8")
provision = (ROOT / "deploy/PROVISION.md").read_text(encoding="utf-8")

ok('name = "taikun-pm"' in pyproject, "pyproject.toml names the taikun-pm application")
ok('requires-python = ">=3.12"' in pyproject, "pyproject.toml pins Python 3.12 floor")
ok("package = false" in pyproject, "tool.uv marks the repo as a non-package application")
ok("[dependency-groups]" in pyproject and "gateway = [" in pyproject,
   "pyproject.toml declares an isolated gateway dependency group")
ok("dev = [" in pyproject and "ruff>=" in pyproject,
   "pyproject.toml declares opt-in dev tooling separate from runtime")
for dep in CORE_DEPS:
    ok(dep in pyproject, f"pyproject.toml lists core runtime dep {dep}")

ok(python_version == "3.12", f".python-version pins 3.12 (got {python_version!r})")

ok(requirements.startswith("# This file was autogenerated by uv"),
   "requirements.txt is a uv export (not hand-edited lower bounds)")
ok("fastapi==" in requirements and "mcp==" in requirements,
   "requirements.txt carries pinned core runtime packages")
ok("litellm" not in requirements,
   "core requirements.txt excludes the gateway-only litellm group")

ok(gateway_requirements.startswith("# This file was autogenerated by uv"),
   "deploy/gateway/requirements.txt is a uv export")
ok("litellm==" in gateway_requirements,
   "gateway requirements export includes litellm")

ok("requires-python>=3.12" in provision.replace(" ", "") or ">=3.12" in provision,
   "PROVISION.md documents the Python 3.12 requirement")

print("ARCH-MS-6 pyproject scaffold checks passed")
