#!/usr/bin/env python3
"""Bounded work_fn for HARDEN-4 unattended dogfood proof.

This is intentionally narrow: it lets an Agent Host prove the full loop against a real
Switchboard task without giving an arbitrary wake payload shell access. The host starts
run_agent.py with --work-module proof_work:run_task, run_session claims a PROOF-lane task,
and this function creates one docs-only PR for that claimed task.
"""
import json
import os
import re
import shutil
import subprocess
import time
from pathlib import Path


def _run(args, cwd=None, check=True):
    proc = subprocess.run(args, cwd=cwd, text=True, capture_output=True, timeout=120)
    if check and proc.returncode != 0:
        raise RuntimeError(
            f"{' '.join(args)} failed with {proc.returncode}: {proc.stderr.strip()}"
        )
    return proc.stdout.strip()


def _slug(value):
    return re.sub(r"[^a-z0-9]+", "-", str(value or "").lower()).strip("-") or "task"


def _task_id(claim):
    task = claim.get("task") or {}
    return claim.get("task_id") or task.get("task_id") or (claim.get("names") or [""])[0]


def _pr_number(url):
    match = re.search(r"/pull/(\d+)", url or "")
    return int(match.group(1)) if match else None


def _now_stamp():
    return os.environ.get("PM_PROOF_NOW") or time.strftime("%Y-%m-%dT%H-%M-%SZ", time.gmtime())


def _repo_url():
    explicit = os.environ.get("PM_PROOF_REPO_URL")
    if explicit:
        return explicit
    return _run(["git", "remote", "get-url", "origin"])


def _proof_root():
    root = Path(os.environ.get("PM_PROOF_WORK_ROOT", "/tmp/switchboard-unattended-proof"))
    root.mkdir(parents=True, exist_ok=True)
    return root


def _fresh_checkout(task_id, branch):
    root = _proof_root()
    worktree = root / _slug(task_id)
    if worktree.exists():
        shutil.rmtree(worktree)
    _run(["git", "clone", _repo_url(), str(worktree)])
    base = os.environ.get("PM_PROOF_BASE_BRANCH", "master")
    _run(["git", "fetch", "origin", base], cwd=worktree)
    _run(["git", "checkout", "-B", branch, f"origin/{base}"], cwd=worktree)
    return worktree


def _proof_markdown(task_id, title, agent_id, runner_session_id, branch):
    payload = {
        "task_id": task_id,
        "title": title,
        "agent_id": agent_id,
        "runner_session_id": runner_session_id,
        "branch": branch,
        "generated_at": _now_stamp(),
        "proof": [
            "Agent Host accepted a lane-scoped wake.",
            "run_agent.py performed handshake, inbox read, and claim_next.",
            "proof_work.py created this docs-only PR without a human editing the file.",
        ],
    }
    return (
        f"# {task_id} unattended proof payload\n\n"
        "This file was generated by `adapters/proof_work.py` during the HARDEN-4 live proof.\n\n"
        "```json\n"
        f"{json.dumps(payload, indent=2, sort_keys=True)}\n"
        "```\n"
    )


def run_task(claim):
    """Create a docs-only PR for the claimed task and return complete_claim evidence."""
    task_id = _task_id(claim)
    if not task_id:
        raise ValueError("claimed task id is required")
    task = claim.get("task") or {}
    title = task.get("title") or task_id
    branch = os.environ.get("PM_PROOF_BRANCH") or f"codex/{task_id}-unattended-proof"
    agent_id = os.environ.get("PM_AGENT_ID", "")
    runner_session_id = os.environ.get("PM_RUNNER_SESSION_ID", "")

    worktree = _fresh_checkout(task_id, branch)
    stamp = _now_stamp()
    proof_file = Path("docs") / "dispatches" / f"{stamp}-{_slug(task_id)}-unattended-proof.md"
    target = worktree / proof_file
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        _proof_markdown(task_id, title, agent_id, runner_session_id, branch),
        encoding="utf-8",
    )

    _run(["git", "add", str(proof_file)], cwd=worktree)
    _run(["git", "commit", "-m", f"docs({task_id}): record unattended proof payload"], cwd=worktree)
    head_sha = _run(["git", "rev-parse", "HEAD"], cwd=worktree)
    _run(["git", "push", "-u", "origin", branch], cwd=worktree)

    body = (
        f"Closes {task_id}.\n\n"
        "Generated by HARDEN-4 unattended proof worker.\n\n"
        f"- Agent: {agent_id or 'unknown'}\n"
        f"- Runner: {runner_session_id or 'unknown'}\n"
        f"- Proof file: {proof_file}\n"
    )
    created = _run([
        "gh", "pr", "create",
        "--base", os.environ.get("PM_PROOF_BASE_BRANCH", "master"),
        "--head", branch,
        "--title", f"docs({task_id}): record unattended proof payload",
        "--body", body,
    ], cwd=worktree, check=False)
    pr_url = ""
    for line in created.splitlines():
        if line.strip().startswith("http"):
            pr_url = line.strip()
            break
    if not pr_url:
        pr_url = _run(["gh", "pr", "view", branch, "--json", "url", "--jq", ".url"], cwd=worktree)

    return {
        "branch": branch,
        "head_sha": head_sha,
        "pr_url": pr_url,
        "pr_number": _pr_number(pr_url),
        "proof_file": str(proof_file),
        "runner_session_id": runner_session_id,
        "agent_id": agent_id,
        "worktree": str(worktree),
    }
