"""Versioned Pydantic contracts shared by REST, MCP, and events (ARCH-MS-25)."""
from . import projects, registry, tasks
from .base import (
    SCHEMA_ID_PREFIX,
    VersionedModel,
    normalize_dependency_ids,
    validation_error_message,
)
from .registry import get_schema, list_schemas, register
from .projects import (
    ARCHIVE_PROJECT_COMMAND_SCHEMA,
    PROJECT_CONSOLIDATION_APPLY_COMMAND_SCHEMA,
    PROJECT_CONSOLIDATION_PLAN_COMMAND_SCHEMA,
    PROJECT_CONSOLIDATION_PLAN_RECEIPT_SCHEMA,
    PROJECT_CONSOLIDATION_PLAN_SCHEMA,
    PROJECT_CONSOLIDATION_ROLLBACK_COMMAND_SCHEMA,
    PROJECT_IMPACT_REPORT_SCHEMA,
    PROJECT_IMPACT_RECEIPT_SCHEMA,
    PROJECT_RECORD_SCHEMA,
    PROJECT_UPDATE_COMMAND_SCHEMA,
    RESTORE_PROJECT_COMMAND_SCHEMA,
    ArchiveProjectCommand,
    ApplyProjectConsolidationCommand,
    ConsolidationApproval,
    PlanProjectConsolidationCommand,
    ProjectImpactReport,
    ProjectImpactReceipt,
    ProjectRecord,
    ProjectUpdateCommand,
    RestoreProjectCommand,
    RollbackProjectConsolidationCommand,
    build_consolidation_plan_receipt,
    build_impact_receipt,
)
from .tasks import (
    CREATE_TASK_COMMAND_SCHEMA,
    GET_TASK_QUERY_SCHEMA,
    UPDATE_TASK_COMMAND_SCHEMA,
    CreateTaskCommand,
    GetTaskQuery,
    UpdateTaskCommand,
)

__all__ = [
    "ARCHIVE_PROJECT_COMMAND_SCHEMA",
    "PROJECT_CONSOLIDATION_APPLY_COMMAND_SCHEMA",
    "PROJECT_CONSOLIDATION_PLAN_COMMAND_SCHEMA",
    "PROJECT_CONSOLIDATION_PLAN_RECEIPT_SCHEMA",
    "PROJECT_CONSOLIDATION_PLAN_SCHEMA",
    "PROJECT_CONSOLIDATION_ROLLBACK_COMMAND_SCHEMA",
    "CREATE_TASK_COMMAND_SCHEMA",
    "GET_TASK_QUERY_SCHEMA",
    "PROJECT_IMPACT_REPORT_SCHEMA",
    "PROJECT_IMPACT_RECEIPT_SCHEMA",
    "PROJECT_RECORD_SCHEMA",
    "PROJECT_UPDATE_COMMAND_SCHEMA",
    "RESTORE_PROJECT_COMMAND_SCHEMA",
    "SCHEMA_ID_PREFIX",
    "UPDATE_TASK_COMMAND_SCHEMA",
    "ArchiveProjectCommand",
    "ApplyProjectConsolidationCommand",
    "ConsolidationApproval",
    "PlanProjectConsolidationCommand",
    "CreateTaskCommand",
    "GetTaskQuery",
    "ProjectImpactReport",
    "ProjectImpactReceipt",
    "ProjectRecord",
    "ProjectUpdateCommand",
    "RestoreProjectCommand",
    "RollbackProjectConsolidationCommand",
    "build_consolidation_plan_receipt",
    "UpdateTaskCommand",
    "VersionedModel",
    "build_impact_receipt",
    "get_schema",
    "list_schemas",
    "normalize_dependency_ids",
    "projects",
    "register",
    "registry",
    "tasks",
    "validation_error_message",
]
